package com.practice.innerclasses;

public class AnonymousTestClass {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		Person person = new Person() {

			@Override
			void print() {
				System.out.println("anonymous class...");

			}
		};
		/*
		 * Internal Class Generated by Compiler
		 * import java.io.PrintStream; static class TestAnonymousInner$1 extends Person
		 * {
		 *  TestAnonymousInner$1(){} 
		 *  void eat() { 
		 *  System.out.println("nice fruits");
		 *   }
		 * }
		 * 
		 */
		person.print();
		AnonymousInner obj = new AnonymousInner() {

			@Override
			public void show() {
				// TODO Auto-generated method stub
				System.out.println("Anonymous class Interface Example ..");
			}
		};
		obj.show();

	}

}
